# Generated by Django 5.0.14 on 2026-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historiquecorrectionkilometrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='document_carte_rose',
            field=models.FileField(blank=True, null=True, upload_to='documents_vehicules/carte_rose/', verbose_name='Scan / photo carte rose'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage_debut',
            field=models.PositiveIntegerField(blank=True, help_text="Kilométrage à l'enregistrement du véhicule", null=True, verbose_name='Kilométrage de début'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_carte_rose',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Numéro carte rose'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_moteur',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Numéro de moteur'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_pneu_arriere_droit',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Pneu arrière droit'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_pneu_arriere_gauche',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Pneu arrière gauche'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_pneu_avant_droit',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Pneu avant droit'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_pneu_avant_gauche',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Pneu avant gauche'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_pneu_secours',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Pneu de secours'),
        ),
    ]
