# Generated by Django 5.0.14 on 2026-09-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vehicule_carte_rose_moteur_pneus_km_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_expiration_permis',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration du permis"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numero_permis',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Numéro de permis'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_permis',
            field=models.ImageField(blank=True, null=True, upload_to='documents_permis/', verbose_name='Photo / scan du permis'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='possede_permis',
            field=models.BooleanField(default=False, verbose_name='Possède un permis de conduire'),
        ),
    ]
