# Generated by Django 5.0.14 on 2026-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_utilisateur_permis_et_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='distance_prevue_km',
            field=models.FloatField(blank=True, help_text="Distance théorique embarquement → destination (vol d'oiseau)", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='embarquement_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='embarquement_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eval_arrivee_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eval_duree_arret_destination_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eval_ecart_trajet_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eval_heure_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eval_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rayon_arrivee_metres',
            field=models.PositiveIntegerField(default=150, help_text="Rayon de la zone d'arrivée autour de la destination (mètres)"),
        ),
    ]
