# Generated by Django 5.0.14 on 2026-09-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0003_reparationmecanique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDevisReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('piece', 'Pièce'), ('main_oeuvre', "Main-d'œuvre"), ('frais', 'Frais / divers'), ('autre', 'Autre')], default='piece', max_length=20, verbose_name='Type')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire ($)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='entretien.reparationmecanique')),
            ],
            options={
                'verbose_name': 'Ligne de devis réparation',
                'verbose_name_plural': 'Lignes de devis réparation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PieceRemplacee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la pièce')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire ($)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entretien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_remplacees', to='entretien.entretien')),
            ],
            options={
                'verbose_name': 'Pièce remplacée',
                'verbose_name_plural': 'Pièces remplacées',
                'ordering': ['nom', 'id'],
            },
        ),
    ]
