# Generated by Django 5.0.14 on 2026-09-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0004_pieces_et_lignes_devis'),
        ('securite', '0002_dossier_incident_photos_lien_reparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparationmecanique',
            name='incident',
            field=models.ForeignKey(blank=True, help_text="Lien vers le rapport d'incident (n° de dossier)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparations', to='securite.incidentsecurite', verbose_name='Dossier incident'),
        ),
        migrations.AddField(
            model_name='reparationmecanique',
            name='numero_dossier',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Recopié depuis l'incident pour suivi devis / réparation", max_length=32, verbose_name='N° de dossier'),
        ),
    ]
