# Generated by Django 5.0.14 on 2026-09-21 17:47

import entretien.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0005_dossier_incident_photos_lien_reparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparationmecanique',
            name='bon_garage',
            field=models.FileField(blank=True, help_text="Photo ou scan du bon d'atelier servant de base au devis", null=True, upload_to=entretien.models.piece_reparation_path, verbose_name='Bon garage (COMIDE, etc.)'),
        ),
    ]
