# Generated by Django 5.0.14 on 2026-09-18 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_utilisateur_permis_et_notif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('date_acces', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_access_logs', to='core.course')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès historique GPS',
                'verbose_name_plural': 'Accès historiques GPS',
                'ordering': ['-date_acces'],
            },
        ),
        migrations.CreateModel(
            name='GPSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_jours', models.PositiveIntegerField(default=365, help_text='Durée de conservation des positions GPS (jours)')),
                ('intervalle_secondes', models.PositiveIntegerField(default=10, help_text='Intervalle recommandé d’envoi (5–15 s)')),
                ('suivi_uniquement_mission_active', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_settings', to='core.etablissement')),
            ],
            options={
                'verbose_name': 'Paramètres GPS',
                'verbose_name_plural': 'Paramètres GPS',
            },
        ),
        migrations.CreateModel(
            name='GPSPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('vitesse', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction en degrés 0-360', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Précision GPS en mètres', null=True)),
                ('kilometrage', models.PositiveIntegerField(blank=True, help_text='Kilométrage GPS / odomètre au moment du point', null=True)),
                ('event_type', models.CharField(choices=[('ping', 'Position'), ('depart', 'Départ'), ('arrivee', 'Arrivée destination'), ('retour', 'Retour'), ('fin', 'Fin de mission')], default='ping', max_length=20)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', help_text='ID client pour déduplication offline', max_length=64)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_gps', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_gps', to='core.course')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_gps', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['course', 'timestamp'], name='gps_gpsposi_course__943a35_idx'), models.Index(fields=['vehicule', 'timestamp'], name='gps_gpsposi_vehicul_67727e_idx'), models.Index(fields=['chauffeur', 'timestamp'], name='gps_gpsposi_chauffe_d30af8_idx')],
            },
        ),
    ]
