# Generated by Django 5.0.14 on 2026-09-20 13:38

import django.db.models.deletion
import securite.models
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def populate_numeros_et_photos(apps, schema_editor):
    IncidentSecurite = apps.get_model('securite', 'IncidentSecurite')
    PhotoIncidentSecurite = apps.get_model('securite', 'PhotoIncidentSecurite')
    for incident in IncidentSecurite.objects.all().order_by('id'):
        if not incident.numero_dossier:
            day = incident.date_signalement.date() if incident.date_signalement else timezone.localdate()
            prefix = f"INC-{day.strftime('%Y%m%d')}-"
            seq = IncidentSecurite.objects.filter(
                numero_dossier__startswith=prefix
            ).count() + 1
            # éviter collision si plusieurs sans numéro
            while IncidentSecurite.objects.filter(numero_dossier=f"{prefix}{seq:04d}").exists():
                seq += 1
            incident.numero_dossier = f"{prefix}{seq:04d}"
            incident.save(update_fields=['numero_dossier'])
        if incident.photo and not PhotoIncidentSecurite.objects.filter(incident=incident).exists():
            PhotoIncidentSecurite.objects.create(incident=incident, image=incident.photo.name)


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentsecurite',
            options={'ordering': ['-date_signalement', '-id'], 'verbose_name': 'Incident sécurité', 'verbose_name_plural': 'Incidents sécurité'},
        ),
        migrations.AddField(
            model_name='incidentsecurite',
            name='clos_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_clos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentsecurite',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentsecurite',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidentsecurite',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentsecurite',
            name='numero_dossier',
            field=models.CharField(
                blank=True, null=True, max_length=32, db_index=True,
                help_text='Référence unique partagée avec devis / réparations',
                verbose_name='N° de dossier',
            ),
        ),
        migrations.AddField(
            model_name='incidentsecurite',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_traites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentsecurite',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo principale (compatibilité). Préférer les pièces jointes multiples.', null=True, upload_to='incidents_securite/'),
        ),
        migrations.AlterField(
            model_name='incidentsecurite',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En traitement'), ('traite', 'Traité'), ('clos', 'Clos')], default='ouvert', max_length=20),
        ),
        migrations.CreateModel(
            name='PhotoIncidentSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=securite.models.incident_photo_path, verbose_name='Image')),
                ('legende', models.CharField(blank=True, default='', max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='securite.incidentsecurite')),
            ],
            options={
                'verbose_name': "Photo d'incident",
                'verbose_name_plural': "Photos d'incident",
                'ordering': ['date_ajout', 'id'],
            },
        ),
        migrations.RunPython(populate_numeros_et_photos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='incidentsecurite',
            name='numero_dossier',
            field=models.CharField(
                blank=True, db_index=True, max_length=32, unique=True,
                help_text='Référence unique partagée avec devis / réparations',
                verbose_name='N° de dossier',
            ),
        ),
    ]
